In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from math import pi

In [104]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, mean_squared_error, mean_absolute_error

In [105]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [106]:
# Load the dataset (Replace 'your_data.csv' with the actual file path)
data = pd.read_csv('RawFishDataMerged.csv',encoding='ISO-8859-1')

In [107]:
# Preview the data
#print(data.head())
data.info()
print(data.columns)
column_names = data.columns.tolist()
print(column_names)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Columns: 790 entries, Fish sample to Unnamed: 789
dtypes: float64(745), object(45)
memory usage: 567.9+ KB
Index(['Fish sample', 'Colour', 'Odour', 'Texture', 'Flavour', 'Appearance',
       'Insect Invasion', 'Overall Acceptability', 'Market', 'State',
       ...
       'Unnamed: 780', 'Unnamed: 781', 'Unnamed: 782', 'Unnamed: 783',
       'Unnamed: 784', 'Unnamed: 785', 'Unnamed: 786', 'Unnamed: 787',
       'Unnamed: 788', 'Unnamed: 789'],
      dtype='object', length=790)
['Fish sample', 'Colour', 'Odour', 'Texture', 'Flavour', 'Appearance', 'Insect Invasion', 'Overall Acceptability', 'Market', 'State', 'TBA', 'PBC', 'TFC', 'Pigmentation1', 'Elevation1', 'Texture1', 'Margin1', 'Shape1', 'Optical Density1', 'Pigmentation2', 'Elevation2', 'Texture2', 'Margin2', 'Shape2', 'Optical Density2', 'Pigmentation3', 'Elevation3', 'Texture3', 'Margin3', 'Shape3', 'Optical Density3', 'pH', 'Lipid oxidation', 'Moisture Content', 'Protein', 'Fat', 'Ash', 'Escherichia coli', 'Salmonella', 'Shigella', 'Staphylococcus', 'Aspergillus flavus', 'Aspergillus occultus', 'Aspergillus niger', 'Aspergillus nidulans ', 'Penicillum chrysogenum', 'Aspergillus fumigatus', 'Rhizopus stolonifer', 'Candida krusei', 'Aspergillus terreus', 'Aspergillus ochraceus', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129', 'Unnamed: 130', 'Unnamed: 131', 'Unnamed: 132', 'Unnamed: 133', 'Unnamed: 134', 'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'Unnamed: 138', 'Unnamed: 139', 'Unnamed: 140', 'Unnamed: 141', 'Unnamed: 142', 'Unnamed: 143', 'Unnamed: 144', 'Unnamed: 145', 'Unnamed: 146', 'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'Unnamed: 150', 'Unnamed: 151', 'Unnamed: 152', 'Unnamed: 153', 'Unnamed: 154', 'Unnamed: 155', 'Unnamed: 156', 'Unnamed: 157', 'Unnamed: 158', 'Unnamed: 159', 'Unnamed: 160', 'Unnamed: 161', 'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169', 'Unnamed: 170', 'Unnamed: 171', 'Unnamed: 172', 'Unnamed: 173', 'Unnamed: 174', 'Unnamed: 175', 'Unnamed: 176', 'Unnamed: 177', 'Unnamed: 178', 'Unnamed: 179', 'Unnamed: 180', 'Unnamed: 181', 'Unnamed: 182', 'Unnamed: 183', 'Unnamed: 184', 'Unnamed: 185', 'Unnamed: 186', 'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190', 'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194', 'Unnamed: 195', 'Unnamed: 196', 'Unnamed: 197', 'Unnamed: 198', 'Unnamed: 199', 'Unnamed: 200', 'Unnamed: 201', 'Unnamed: 202', 'Unnamed: 203', 'Unnamed: 204', 'Unnamed: 205', 'Unnamed: 206', 'Unnamed: 207', 'Unnamed: 208', 'Unnamed: 209', 'Unnamed: 210', 'Unnamed: 211', 'Unnamed: 212', 'Unnamed: 213', 'Unnamed: 214', 'Unnamed: 215', 'Unnamed: 216', 'Unnamed: 217', 'Unnamed: 218', 'Unnamed: 219', 'Unnamed: 220', 'Unnamed: 221', 'Unnamed: 222', 'Unnamed: 223', 'Unnamed: 224', 'Unnamed: 225', 'Unnamed: 226', 'Unnamed: 227', 'Unnamed: 228', 'Unnamed: 229', 'Unnamed: 230', 'Unnamed: 231', 'Unnamed: 232', 'Unnamed: 233', 'Unnamed: 234', 'Unnamed: 235', 'Unnamed: 236', 'Unnamed: 237', 'Unnamed: 238', 'Unnamed: 239', 'Unnamed: 240', 'Unnamed: 241', 'Unnamed: 242', 'Unnamed: 243', 'Unnamed: 244', 'Unnamed: 245', 'Unnamed: 246', 'Unnamed: 247', 'Unnamed: 248', 'Unnamed: 249', 'Unnamed: 250', 'Unnamed: 251', 'Unnamed: 252', 'Unnamed: 253', 'Unnamed: 254', 'Unnamed: 255', 'Unnamed: 256', 'Unnamed: 257', 'Unnamed: 258', 'Unnamed: 259', 'Unnamed: 260', 'Unnamed: 261', 'Unnamed: 262', 'Unnamed: 263', 'Unnamed: 264', 'Unnamed: 265', 'Unnamed: 266', 'Unnamed: 267', 'Unnamed: 268', 'Unnamed: 269', 'Unnamed: 270', 'Unnamed: 271', 'Unnamed: 272', 'Unnamed: 273', 'Unnamed: 274', 'Unnamed: 275', 'Unnamed: 276', 'Unnamed: 277', 'Unnamed: 278', 'Unnamed: 279', 'Unnamed: 280', 'Unnamed: 281', 'Unnamed: 282', 'Unnamed: 283', 'Unnamed: 284', 'Unnamed: 285', 'Unnamed: 286', 'Unnamed: 287', 'Unnamed: 288', 'Unnamed: 289', 'Unnamed: 290', 'Unnamed: 291', 'Unnamed: 292', 'Unnamed: 293', 'Unnamed: 294', 'Unnamed: 295', 'Unnamed: 296', 'Unnamed: 297', 'Unnamed: 298', 'Unnamed: 299', 'Unnamed: 300', 'Unnamed: 301', 'Unnamed: 302', 'Unnamed: 303', 'Unnamed: 304', 'Unnamed: 305', 'Unnamed: 306', 'Unnamed: 307', 'Unnamed: 308', 'Unnamed: 309', 'Unnamed: 310', 'Unnamed: 311', 'Unnamed: 312', 'Unnamed: 313', 'Unnamed: 314', 'Unnamed: 315', 'Unnamed: 316', 'Unnamed: 317', 'Unnamed: 318', 'Unnamed: 319', 'Unnamed: 320', 'Unnamed: 321', 'Unnamed: 322', 'Unnamed: 323', 'Unnamed: 324', 'Unnamed: 325', 'Unnamed: 326', 'Unnamed: 327', 'Unnamed: 328', 'Unnamed: 329', 'Unnamed: 330', 'Unnamed: 331', 'Unnamed: 332', 'Unnamed: 333', 'Unnamed: 334', 'Unnamed: 335', 'Unnamed: 336', 'Unnamed: 337', 'Unnamed: 338', 'Unnamed: 339', 'Unnamed: 340', 'Unnamed: 341', 'Unnamed: 342', 'Unnamed: 343', 'Unnamed: 344', 'Unnamed: 345', 'Unnamed: 346', 'Unnamed: 347', 'Unnamed: 348', 'Unnamed: 349', 'Unnamed: 350', 'Unnamed: 351', 'Unnamed: 352', 'Unnamed: 353', 'Unnamed: 354', 'Unnamed: 355', 'Unnamed: 356', 'Unnamed: 357', 'Unnamed: 358', 'Unnamed: 359', 'Unnamed: 360', 'Unnamed: 361', 'Unnamed: 362', 'Unnamed: 363', 'Unnamed: 364', 'Unnamed: 365', 'Unnamed: 366', 'Unnamed: 367', 'Unnamed: 368', 'Unnamed: 369', 'Unnamed: 370', 'Unnamed: 371', 'Unnamed: 372', 'Unnamed: 373', 'Unnamed: 374', 'Unnamed: 375', 'Unnamed: 376', 'Unnamed: 377', 'Unnamed: 378', 'Unnamed: 379', 'Unnamed: 380', 'Unnamed: 381', 'Unnamed: 382', 'Unnamed: 383', 'Unnamed: 384', 'Unnamed: 385', 'Unnamed: 386', 'Unnamed: 387', 'Unnamed: 388', 'Unnamed: 389', 'Unnamed: 390', 'Unnamed: 391', 'Unnamed: 392', 'Unnamed: 393', 'Unnamed: 394', 'Unnamed: 395', 'Unnamed: 396', 'Unnamed: 397', 'Unnamed: 398', 'Unnamed: 399', 'Unnamed: 400', 'Unnamed: 401', 'Unnamed: 402', 'Unnamed: 403', 'Unnamed: 404', 'Unnamed: 405', 'Unnamed: 406', 'Unnamed: 407', 'Unnamed: 408', 'Unnamed: 409', 'Unnamed: 410', 'Unnamed: 411', 'Unnamed: 412', 'Unnamed: 413', 'Unnamed: 414', 'Unnamed: 415', 'Unnamed: 416', 'Unnamed: 417', 'Unnamed: 418', 'Unnamed: 419', 'Unnamed: 420', 'Unnamed: 421', 'Unnamed: 422', 'Unnamed: 423', 'Unnamed: 424', 'Unnamed: 425', 'Unnamed: 426', 'Unnamed: 427', 'Unnamed: 428', 'Unnamed: 429', 'Unnamed: 430', 'Unnamed: 431', 'Unnamed: 432', 'Unnamed: 433', 'Unnamed: 434', 'Unnamed: 435', 'Unnamed: 436', 'Unnamed: 437', 'Unnamed: 438', 'Unnamed: 439', 'Unnamed: 440', 'Unnamed: 441', 'Unnamed: 442', 'Unnamed: 443', 'Unnamed: 444', 'Unnamed: 445', 'Unnamed: 446', 'Unnamed: 447', 'Unnamed: 448', 'Unnamed: 449', 'Unnamed: 450', 'Unnamed: 451', 'Unnamed: 452', 'Unnamed: 453', 'Unnamed: 454', 'Unnamed: 455', 'Unnamed: 456', 'Unnamed: 457', 'Unnamed: 458', 'Unnamed: 459', 'Unnamed: 460', 'Unnamed: 461', 'Unnamed: 462', 'Unnamed: 463', 'Unnamed: 464', 'Unnamed: 465', 'Unnamed: 466', 'Unnamed: 467', 'Unnamed: 468', 'Unnamed: 469', 'Unnamed: 470', 'Unnamed: 471', 'Unnamed: 472', 'Unnamed: 473', 'Unnamed: 474', 'Unnamed: 475', 'Unnamed: 476', 'Unnamed: 477', 'Unnamed: 478', 'Unnamed: 479', 'Unnamed: 480', 'Unnamed: 481', 'Unnamed: 482', 'Unnamed: 483', 'Unnamed: 484', 'Unnamed: 485', 'Unnamed: 486', 'Unnamed: 487', 'Unnamed: 488', 'Unnamed: 489', 'Unnamed: 490', 'Unnamed: 491', 'Unnamed: 492', 'Unnamed: 493', 'Unnamed: 494', 'Unnamed: 495', 'Unnamed: 496', 'Unnamed: 497', 'Unnamed: 498', 'Unnamed: 499', 'Unnamed: 500', 'Unnamed: 501', 'Unnamed: 502', 'Unnamed: 503', 'Unnamed: 504', 'Unnamed: 505', 'Unnamed: 506', 'Unnamed: 507', 'Unnamed: 508', 'Unnamed: 509', 'Unnamed: 510', 'Unnamed: 511', 'Unnamed: 512', 'Unnamed: 513', 'Unnamed: 514', 'Unnamed: 515', 'Unnamed: 516', 'Unnamed: 517', 'Unnamed: 518', 'Unnamed: 519', 'Unnamed: 520', 'Unnamed: 521', 'Unnamed: 522', 'Unnamed: 523', 'Unnamed: 524', 'Unnamed: 525', 'Unnamed: 526', 'Unnamed: 527', 'Unnamed: 528', 'Unnamed: 529', 'Unnamed: 530', 'Unnamed: 531', 'Unnamed: 532', 'Unnamed: 533', 'Unnamed: 534', 'Unnamed: 535', 'Unnamed: 536', 'Unnamed: 537', 'Unnamed: 538', 'Unnamed: 539', 'Unnamed: 540', 'Unnamed: 541', 'Unnamed: 542', 'Unnamed: 543', 'Unnamed: 544', 'Unnamed: 545', 'Unnamed: 546', 'Unnamed: 547', 'Unnamed: 548', 'Unnamed: 549', 'Unnamed: 550', 'Unnamed: 551', 'Unnamed: 552', 'Unnamed: 553', 'Unnamed: 554', 'Unnamed: 555', 'Unnamed: 556', 'Unnamed: 557', 'Unnamed: 558', 'Unnamed: 559', 'Unnamed: 560', 'Unnamed: 561', 'Unnamed: 562', 'Unnamed: 563', 'Unnamed: 564', 'Unnamed: 565', 'Unnamed: 566', 'Unnamed: 567', 'Unnamed: 568', 'Unnamed: 569', 'Unnamed: 570', 'Unnamed: 571', 'Unnamed: 572', 'Unnamed: 573', 'Unnamed: 574', 'Unnamed: 575', 'Unnamed: 576', 'Unnamed: 577', 'Unnamed: 578', 'Unnamed: 579', 'Unnamed: 580', 'Unnamed: 581', 'Unnamed: 582', 'Unnamed: 583', 'Unnamed: 584', 'Unnamed: 585', 'Unnamed: 586', 'Unnamed: 587', 'Unnamed: 588', 'Unnamed: 589', 'Unnamed: 590', 'Unnamed: 591', 'Unnamed: 592', 'Unnamed: 593', 'Unnamed: 594', 'Unnamed: 595', 'Unnamed: 596', 'Unnamed: 597', 'Unnamed: 598', 'Unnamed: 599', 'Unnamed: 600', 'Unnamed: 601', 'Unnamed: 602', 'Unnamed: 603', 'Unnamed: 604', 'Unnamed: 605', 'Unnamed: 606', 'Unnamed: 607', 'Unnamed: 608', 'Unnamed: 609', 'Unnamed: 610', 'Unnamed: 611', 'Unnamed: 612', 'Unnamed: 613', 'Unnamed: 614', 'Unnamed: 615', 'Unnamed: 616', 'Unnamed: 617', 'Unnamed: 618', 'Unnamed: 619', 'Unnamed: 620', 'Unnamed: 621', 'Unnamed: 622', 'Unnamed: 623', 'Unnamed: 624', 'Unnamed: 625', 'Unnamed: 626', 'Unnamed: 627', 'Unnamed: 628', 'Unnamed: 629', 'Unnamed: 630', 'Unnamed: 631', 'Unnamed: 632', 'Unnamed: 633', 'Unnamed: 634', 'Unnamed: 635', 'Unnamed: 636', 'Unnamed: 637', 'Unnamed: 638', 'Unnamed: 639', 'Unnamed: 640', 'Unnamed: 641', 'Unnamed: 642', 'Unnamed: 643', 'Unnamed: 644', 'Unnamed: 645', 'Unnamed: 646', 'Unnamed: 647', 'Unnamed: 648', 'Unnamed: 649', 'Unnamed: 650', 'Unnamed: 651', 'Unnamed: 652', 'Unnamed: 653', 'Unnamed: 654', 'Unnamed: 655', 'Unnamed: 656', 'Unnamed: 657', 'Unnamed: 658', 'Unnamed: 659', 'Unnamed: 660', 'Unnamed: 661', 'Unnamed: 662', 'Unnamed: 663', 'Unnamed: 664', 'Unnamed: 665', 'Unnamed: 666', 'Unnamed: 667', 'Unnamed: 668', 'Unnamed: 669', 'Unnamed: 670', 'Unnamed: 671', 'Unnamed: 672', 'Unnamed: 673', 'Unnamed: 674', 'Unnamed: 675', 'Unnamed: 676', 'Unnamed: 677', 'Unnamed: 678', 'Unnamed: 679', 'Unnamed: 680', 'Unnamed: 681', 'Unnamed: 682', 'Unnamed: 683', 'Unnamed: 684', 'Unnamed: 685', 'Unnamed: 686', 'Unnamed: 687', 'Unnamed: 688', 'Unnamed: 689', 'Unnamed: 690', 'Unnamed: 691', 'Unnamed: 692', 'Unnamed: 693', 'Unnamed: 694', 'Unnamed: 695', 'Unnamed: 696', 'Unnamed: 697', 'Unnamed: 698', 'Unnamed: 699', 'Unnamed: 700', 'Unnamed: 701', 'Unnamed: 702', 'Unnamed: 703', 'Unnamed: 704', 'Unnamed: 705', 'Unnamed: 706', 'Unnamed: 707', 'Unnamed: 708', 'Unnamed: 709', 'Unnamed: 710', 'Unnamed: 711', 'Unnamed: 712', 'Unnamed: 713', 'Unnamed: 714', 'Unnamed: 715', 'Unnamed: 716', 'Unnamed: 717', 'Unnamed: 718', 'Unnamed: 719', 'Unnamed: 720', 'Unnamed: 721', 'Unnamed: 722', 'Unnamed: 723', 'Unnamed: 724', 'Unnamed: 725', 'Unnamed: 726', 'Unnamed: 727', 'Unnamed: 728', 'Unnamed: 729', 'Unnamed: 730', 'Unnamed: 731', 'Unnamed: 732', 'Unnamed: 733', 'Unnamed: 734', 'Unnamed: 735', 'Unnamed: 736', 'Unnamed: 737', 'Unnamed: 738', 'Unnamed: 739', 'Unnamed: 740', 'Unnamed: 741', 'Unnamed: 742', 'Unnamed: 743', 'Unnamed: 744', 'Unnamed: 745', 'Unnamed: 746', 'Unnamed: 747', 'Unnamed: 748', 'Unnamed: 749', 'Unnamed: 750', 'Unnamed: 751', 'Unnamed: 752', 'Unnamed: 753', 'Unnamed: 754', 'Unnamed: 755', 'Unnamed: 756', 'Unnamed: 757', 'Unnamed: 758', 'Unnamed: 759', 'Unnamed: 760', 'Unnamed: 761', 'Unnamed: 762', 'Unnamed: 763', 'Unnamed: 764', 'Unnamed: 765', 'Unnamed: 766', 'Unnamed: 767', 'Unnamed: 768', 'Unnamed: 769', 'Unnamed: 770', 'Unnamed: 771', 'Unnamed: 772', 'Unnamed: 773', 'Unnamed: 774', 'Unnamed: 775', 'Unnamed: 776', 'Unnamed: 777', 'Unnamed: 778', 'Unnamed: 779', 'Unnamed: 780', 'Unnamed: 781', 'Unnamed: 782', 'Unnamed: 783', 'Unnamed: 784', 'Unnamed: 785', 'Unnamed: 786', 'Unnamed: 787', 'Unnamed: 788', 'Unnamed: 789']

In [108]:
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]

In [109]:
column_names = data.columns.tolist()
print(column_names)

['Fish sample', 'Colour', 'Odour', 'Texture', 'Flavour', 'Appearance', 'Insect Invasion', 'Overall Acceptability', 'Market', 'State', 'TBA', 'PBC', 'TFC', 'Pigmentation1', 'Elevation1', 'Texture1', 'Margin1', 'Shape1', 'Optical Density1', 'Pigmentation2', 'Elevation2', 'Texture2', 'Margin2', 'Shape2', 'Optical Density2', 'Pigmentation3', 'Elevation3', 'Texture3', 'Margin3', 'Shape3', 'Optical Density3', 'pH', 'Lipid oxidation', 'Moisture Content', 'Protein', 'Fat', 'Ash', 'Escherichia coli', 'Salmonella', 'Shigella', 'Staphylococcus', 'Aspergillus flavus', 'Aspergillus occultus', 'Aspergillus niger', 'Aspergillus nidulans ', 'Penicillum chrysogenum', 'Aspergillus fumigatus', 'Rhizopus stolonifer', 'Candida krusei', 'Aspergillus terreus', 'Aspergillus ochraceus']

In [110]:
data.head()

,Fish sample,Colour,Odour,Texture,Flavour,Appearance,Insect Invasion,Overall Acceptability,Market,State,...,Aspergillus flavus,Aspergillus occultus,Aspergillus niger,Aspergillus nidulans,Penicillum chrysogenum,Aspergillus fumigatus,Rhizopus stolonifer,Candida krusei,Aspergillus terreus,Aspergillus ochraceus
0,FAM1,Dark Brown,Moderate,Moderate,Good,Attractive,Absent,Moderate,Mandate,Kwara,...,Present,Present,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Absent
1,FAM2,Dark,Very Good,Hard,Good,Very Attractive,Absent,Very High,Mandate,Kwara,...,Present,Present,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Absent
2,FAM3,Dark,Good,Very hard,Very Good,Not Attractive,Absent,High,Mandate,Kwara,...,Present,Present,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Absent
3,FAT1,Dark Brown,Very Good,Very Hard,Very Good,Very Attractive,Absent,Very High,Oja Titun,Kwara,...,Present,Present,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Absent
4,FAT2,Light Brown,Moderate,Moderate,Good,Not Attractive,Absent,Low,Oja Titun,Kwara,...,Absent,Present,Absent,Absent,Absent,Absent,Absent,Absent,Absent,Absent

In [111]:
df = pd.DataFrame(data)
#df = df.replace(mapping)
# Separate float fields for later use
# Separate float and integer fields for later use
numeric_fields = df.select_dtypes(include=['float64', 'int64'])

# Drop numeric columns to prepare for encoding only categorical fields
df_to_encode = df.select_dtypes(exclude=['float64', 'int64'])

# Ensure that all categorical columns are strings (to prevent errors)
df_to_encode = df_to_encode.astype(str)

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each column in the categorical DataFrame
for column in df_to_encode.columns:
    df_to_encode[column] = le.fit_transform(df_to_encode[column])

# Merge the encoded fields and the numeric fields back together
#df_merged = pd.concat([df_to_encode, numeric_fields], axis=1)

In [112]:
df_to_encode.head(10)

,Fish sample,Colour,Odour,Texture,Flavour,Appearance,Insect Invasion,Overall Acceptability,Market,State,...,Aspergillus flavus,Aspergillus occultus,Aspergillus niger,Aspergillus nidulans,Penicillum chrysogenum,Aspergillus fumigatus,Rhizopus stolonifer,Candida krusei,Aspergillus terreus,Aspergillus ochraceus
0,3,7,5,4,1,1,0,11,20,3,...,1,1,0,0,0,0,0,0,0,0
1,4,4,9,1,1,6,0,13,20,3,...,1,1,0,0,0,0,0,0,0,0
2,5,4,2,12,8,5,0,7,20,3,...,1,1,0,0,0,0,0,0,0,0
3,9,6,9,10,8,6,0,13,24,3,...,1,1,0,0,0,0,0,0,0,0
4,10,10,6,4,1,5,0,9,24,3,...,0,1,0,0,0,0,0,0,0,0
5,11,6,5,1,3,1,0,11,24,3,...,0,1,0,0,0,0,0,0,0,0
6,6,9,3,10,4,5,0,10,23,3,...,0,1,0,0,0,0,0,0,0,0
7,7,6,3,4,1,1,0,13,23,3,...,0,1,0,0,0,0,0,0,0,0
8,8,9,2,10,4,1,0,12,23,3,...,1,1,0,0,0,0,0,0,0,0
9,0,9,1,10,7,1,4,7,12,3,...,1,1,0,0,0,0,0,0,0,0

In [113]:
X = pd.concat([df_to_encode, numeric_fields], axis=1)

# Target variable (without OneHotEncoding)
y = df_to_encode[['Escherichia coli', 'Salmonella', 'Shigella', 'Staphylococcus',
        'Aspergillus flavus', 'Aspergillus occultus', 'Aspergillus niger',
        'Aspergillus nidulans ', 'Penicillum chrysogenum', 'Aspergillus fumigatus',
        'Rhizopus stolonifer', 'Candida krusei', 'Aspergillus terreus', 'Aspergillus ochraceus']]

In [114]:
print(X.isna().sum())
print(y.isna().sum())

Fish sample               0
Colour                    0
Odour                     0
Texture                   0
Flavour                   0
Appearance                0
Insect Invasion           0
Overall Acceptability     0
Market                    0
State                     0
TBA                       0
PBC                       0
TFC                       0
Pigmentation1             0
Elevation1                0
Texture1                  0
Margin1                   0
Shape1                    0
Optical Density1          0
Pigmentation2             0
Elevation2                0
Texture2                  0
Margin2                   0
Shape2                    0
Optical Density2          0
Pigmentation3             0
Elevation3                0
Texture3                  0
Margin3                   0
Shape3                    0
Optical Density3          0
Escherichia coli          0
Salmonella                0
Shigella                  0
Staphylococcus            0
Aspergillus flavus        0
Aspergillus occultus      0
Aspergillus niger         0
Aspergillus nidulans      0
Penicillum chrysogenum    0
Aspergillus fumigatus     0
Rhizopus stolonifer       0
Candida krusei            0
Aspergillus terreus       0
Aspergillus ochraceus     0
pH                        2
Lipid oxidation           2
Moisture Content          2
Protein                   2
Fat                       2
Ash                       2
dtype: int64
Escherichia coli          0
Salmonella                0
Shigella                  0
Staphylococcus            0
Aspergillus flavus        0
Aspergillus occultus      0
Aspergillus niger         0
Aspergillus nidulans      0
Penicillum chrysogenum    0
Aspergillus fumigatus     0
Rhizopus stolonifer       0
Candida krusei            0
Aspergillus terreus       0
Aspergillus ochraceus     0
dtype: int64

In [115]:
# Handle NaN in numeric columns of X by filling with the mean of each column
numeric_columns_X = X.select_dtypes(include=np.number).columns
X[numeric_columns_X] = X[numeric_columns_X].fillna(X[numeric_columns_X].mean())

# Handle NaN in categorical columns of X by filling with the most frequent value (mode)
categorical_columns_X = X.select_dtypes(exclude=np.number).columns
for column in categorical_columns_X:
    X[column] = X[column].fillna(X[column].mode()[0])

# Handle NaN in numeric columns of y by filling with the mean of each column
numeric_columns_y = y.select_dtypes(include=np.number).columns
y[numeric_columns_y] = y[numeric_columns_y].fillna(y[numeric_columns_y].mean())

C:\Users\User1\AppData\Local\Temp\ipykernel_1504\485909721.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[numeric_columns_y] = y[numeric_columns_y].fillna(y[numeric_columns_y].mean())

In [116]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 51 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fish sample             92 non-null     int32
 1   Colour                  92 non-null     int32
 2   Odour                   92 non-null     int32
 3   Texture                 92 non-null     int32
 4   Flavour                 92 non-null     int32
 5   Appearance              92 non-null     int32
 6   Insect Invasion         92 non-null     int32
 7   Overall Acceptability   92 non-null     int32
 8   Market                  92 non-null     int32
 9   State                   92 non-null     int32
 10  TBA                     92 non-null     int32
 11  PBC                     92 non-null     int32
 12  TFC                     92 non-null     int32
 13  Pigmentation1           92 non-null     int32
 14  Elevation1              92 non-null     int32
 15  Texture1                92 non-null     int32
 16  Margin1                 92 non-null     int32
 17  Shape1                  92 non-null     int32
 18  Optical Density1        92 non-null     int32
 19  Pigmentation2           92 non-null     int32
 20  Elevation2              92 non-null     int32
 21  Texture2                92 non-null     int32
 22  Margin2                 92 non-null     int32
 23  Shape2                  92 non-null     int32
 24  Optical Density2        92 non-null     int32
 25  Pigmentation3           92 non-null     int32
 26  Elevation3              92 non-null     int32
 27  Texture3                92 non-null     int32
 28  Margin3                 92 non-null     int32
 29  Shape3                  92 non-null     int32
 30  Optical Density3        92 non-null     int32
 31  Escherichia coli        92 non-null     int32
 32  Salmonella              92 non-null     int32
 33  Shigella                92 non-null     int32
 34  Staphylococcus          92 non-null     int32
 35  Aspergillus flavus      92 non-null     int32
 36  Aspergillus occultus    92 non-null     int32
 37  Aspergillus niger       92 non-null     int32
 38  Aspergillus nidulans    92 non-null     int32
 39  Penicillum chrysogenum  92 non-null     int32
 40  Aspergillus fumigatus   92 non-null     int32
 41  Rhizopus stolonifer     92 non-null     int32
 42  Candida krusei          92 non-null     int32
 43  Aspergillus terreus     92 non-null     int32
 44  Aspergillus ochraceus   92 non-null     int32
 45  pH                      92 non-null     float64
 46  Lipid oxidation         92 non-null     float64
 47  Moisture Content        92 non-null     float64
 48  Protein                 92 non-null     float64
 49  Fat                     92 non-null     float64
 50  Ash                     92 non-null     float64
dtypes: float64(6), int32(45)
memory usage: 20.6 KB

In [117]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Escherichia coli        92 non-null     int32
 1   Salmonella              92 non-null     int32
 2   Shigella                92 non-null     int32
 3   Staphylococcus          92 non-null     int32
 4   Aspergillus flavus      92 non-null     int32
 5   Aspergillus occultus    92 non-null     int32
 6   Aspergillus niger       92 non-null     int32
 7   Aspergillus nidulans    92 non-null     int32
 8   Penicillum chrysogenum  92 non-null     int32
 9   Aspergillus fumigatus   92 non-null     int32
 10  Rhizopus stolonifer     92 non-null     int32
 11  Candida krusei          92 non-null     int32
 12  Aspergillus terreus     92 non-null     int32
 13  Aspergillus ochraceus   92 non-null     int32
dtypes: int32(14)
memory usage: 5.2 KB

In [118]:
print(X.isna().sum())
print(y.isna().sum())

Fish sample               0
Colour                    0
Odour                     0
Texture                   0
Flavour                   0
Appearance                0
Insect Invasion           0
Overall Acceptability     0
Market                    0
State                     0
TBA                       0
PBC                       0
TFC                       0
Pigmentation1             0
Elevation1                0
Texture1                  0
Margin1                   0
Shape1                    0
Optical Density1          0
Pigmentation2             0
Elevation2                0
Texture2                  0
Margin2                   0
Shape2                    0
Optical Density2          0
Pigmentation3             0
Elevation3                0
Texture3                  0
Margin3                   0
Shape3                    0
Optical Density3          0
Escherichia coli          0
Salmonella                0
Shigella                  0
Staphylococcus            0
Aspergillus flavus        0
Aspergillus occultus      0
Aspergillus niger         0
Aspergillus nidulans      0
Penicillum chrysogenum    0
Aspergillus fumigatus     0
Rhizopus stolonifer       0
Candida krusei            0
Aspergillus terreus       0
Aspergillus ochraceus     0
pH                        0
Lipid oxidation           0
Moisture Content          0
Protein                   0
Fat                       0
Ash                       0
dtype: int64
Escherichia coli          0
Salmonella                0
Shigella                  0
Staphylococcus            0
Aspergillus flavus        0
Aspergillus occultus      0
Aspergillus niger         0
Aspergillus nidulans      0
Penicillum chrysogenum    0
Aspergillus fumigatus     0
Rhizopus stolonifer       0
Candida krusei            0
Aspergillus terreus       0
Aspergillus ochraceus     0
dtype: int64

In [119]:
# Scale numeric features
scaler = MinMaxScaler()
X[X.select_dtypes(include=['float64', 'int64']).columns] = scaler.fit_transform(X.select_dtypes(include=['float64', 'int64']))

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the regression model
model = RandomForestRegressor(random_state=42)

In [120]:
# Train the model
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

In [121]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.05219323308270678

In [122]:

# Calculate RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

# Calculate MAE
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")

Root Mean Squared Error: 0.22845838369976001
Mean Absolute Error: 0.1249624060150376

In [124]:
import pickle
file_path = 'microbial_modelreg.pkl'
with open(file_path, 'wb') as file:
    pickle.dump(model, file)
print(f"Model saved to {file_path}")

Model saved to microbial_modelreg.pkl

In [126]:
with open('scalers.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)